spring:
  application:
    name: Fuel Net


  datasource:
#    url: jdbc:postgresql://localhost:5432/fuel_net
    url: jdbc:postgresql://ep-snowy-cake-adjc3va7-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
#    username: postgres
#    password: root
    password: npg_Cs2aOo5XFYRp
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
